### ISSUE TITLE
bundle: command not found

### ISSUE THREAD

**Issue by imgarylai** [seuros/capistrano-sidekiq#124]
When I deployed my app, I got messages below:

I tried to run the same command on my server. It works. Actually, when I first time deployed to the server, I didn't get this message. However, When I updated my code and tried to deploy again. Things happened. 

```sh
INFO [0cce9ccd] Running bundle exec sidekiq --index 0 --pidfile /home/ubuntu/app/shared/tmp/pids/sidekiq-0.pid --environment production --logfile /home/ubuntu/app/shared/log/sidekiq.log --daemon as ubuntu@52.192.125.253
DEBUG [0cce9ccd] Command: cd /home/ubuntu/app/releases/20151112015016 && ( RBENV_ROOT=~/.rbenv RBENV_VERSION=2.2.3 bundle exec sidekiq --index 0 --pidfile /home/ubuntu/app/shared/tmp/pids/sidekiq-0.pid --environment production --logfile /home/ubuntu/app/shared/log/sidekiq.log --daemon )
DEBUG [0cce9ccd] 	bash: bundle: command not found
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as ubuntu@52.192.125.253: sidekiq exit status: 127
sidekiq stdout: Nothing written
sidekiq stderr: bash: bundle: command not found
/Users/gary/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:16:in `rescue in block (2 levels) in execute'
/Users/gary/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
SSHKit::Command::Failed: sidekiq exit status: 127
sidekiq stdout: Nothing written
sidekiq stderr: bash: bundle: command not found
/Users/gary/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/command.rb:95:in `exit_status='
/Users/gary/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:179:in `block in _execute'
/Users/gary/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:133:in `tap'
/Users/gary/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:133:in `_execute'
/Users/gary/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:66:in `execute'
/Users/gary/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/capistrano-sidekiq-b5155675554e/lib/capistrano/tasks/sidekiq.rake:118:in `start_sidekiq'
/Users/gary/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/capistrano-sidekiq-b5155675554e/lib/capistrano/tasks/sidekiq.rake:164:in `block (5 levels) in <top (required)>'
/Users/gary/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/capistrano-sidekiq-b5155675554e/lib/capistrano/tasks/sidekiq.rake:37:in `block (2 levels) in for_each_process'
/Users/gary/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/abstract.rb:77:in `within'
/Users/gary/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/capistrano-sidekiq-b5155675554e/lib/capistrano/tasks/sidekiq.rake:36:in `block in for_each_process'
/Users/gary/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/capistrano-sidekiq-b5155675554e/lib/capistrano/tasks/sidekiq.rake:35:in `each'
/Users/gary/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/capistrano-sidekiq-b5155675554e/lib/capistrano/tasks/sidekiq.rake:35:in `each_with_index'
/Users/gary/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/capistrano-sidekiq-b5155675554e/lib/capistrano/tasks/sidekiq.rake:35:in `for_each_process'
/Users/gary/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/capistrano-sidekiq-b5155675554e/lib/capistrano/tasks/sidekiq.rake:163:in `block (4 levels) in <top (required)>'
/Users/gary/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/capistrano-sidekiq-b5155675554e/lib/capistrano/tasks/sidekiq.rake:221:in `call'
/Users/gary/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/capistrano-sidekiq-b5155675554e/lib/capistrano/tasks/sidekiq.rake:221:in `switch_user'
/Users/gary/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/capistrano-sidekiq-b5155675554e/lib/capistrano/tasks/sidekiq.rake:162:in `block (3 levels) in <top (required)>'
/Users/gary/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Users/gary/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/gary/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
Tasks: TOP => sidekiq:start
The deploy has failed with an error: Exception while executing as ubuntu@52.192.125.253: sidekiq exit status: 127
sidekiq stdout: Nothing written
sidekiq stderr: bash: bundle: command not found
** Invoke deploy:failed (first_time)
** Execute deploy:failed
```

**Comment by AmirolAhmad** [comment]
same as here `Running bundle exec bundle exec sidekiq --index 0 --pidfile` <-- problem here

**Comment by imgarylai** [comment]
@AmirolAhmad Thanks, I got same errors when reverted back to 0.5.3. Should I do anything else?

**Comment by gerodp** [comment]
Hello,

I'm having a similar problem. In my case I see this difference:

0.5.3
/home/cg/trip-app/rvm1scripts/rvm-auto.sh . bundle exec sidekiq --index 0 --pidfile

0.5.4
bundle exec sidekiq --index 0 --pidfile

**Comment by seuros** [comment]
@gerodp, for rvm , you either have to use capistrano/rvm or update the rvm1-capistrano gem.

**Comment by gerodp** [comment]
Yes, in fact I am using rvm1-capistrano but after updating the version of capistrano-sidekiq the command generated is not taking rvm-auto.sh anymore into account.

**Comment by tirdadc** [comment]
Running into this issue and I already had `gem 'capistrano-rvm'` included along with the require in my Capfile.

```
bundle exec sidekiq --index 0 --pidfile /var/www/prod/PROJECT/shared/tmp/pids/sidekiq-0.pid --environment production --logfile /var/www/prod/PROJECT/shared/log/sidekiq.log --daemon
```
This command works just fine when I execute it manually.

I tried switching to https://github.com/capistrano/rvm but it resulted in the same issue.

**Comment by imgarylai** [comment]
After I reverted to `v0.5.3`, it works. But I use `rbenv`.

**Comment by imgarylai** [comment]
``` sh
# v0.5.4
cd /home/ubuntu/app/current && ( RBENV_ROOT=~/.rbenv RBENV_VERSION=2.2.3 bundle exec sidekiq --index 0 --pidfile /home/ubuntu/app/shared/tmp/pids/sidekiq-0.pid --environment production --logfile /home/ubuntu/app/shared/log/sidekiq.log --daemon )
```
``` sh
# v0.5.3
cd /home/ubuntu/app/current && ( RBENV_ROOT=~/.rbenv RBENV_VERSION=2.2.3 ~/.rbenv/bin/rbenv exec bundle exec sidekiq --index 0 --pidfile /home/ubuntu/app/shared/tmp/pids/sidekiq.pid --environment production --logfile /home/ubuntu/app/shared/log/sidekiq.log --daemon )
```

**Comment by ArturT** [comment]
I have the same problem with rbenv:

```bash
# 0.5.4
bundle exec sidekiq --index 0 --pidfile /home/deploy/apps/app/shared/tmp/pids/sidekiq-0.pid --environment staging --logfile /home/deploy/apps/app/shared/log/sidekiq.log --daemon

# 0.5.3 - it works
RBENV_ROOT=/usr/local/rbenv RBENV_VERSION=2.2.3 /usr/local/rbenv/bin/rbenv exec bundle exec sidekiq --index 0 --pidfile /home/deploy/apps/app/shared/tmp/pids/sidekiq.pid --environment staging --logfile /home/deploy/apps/app/shared/log/sidekiq.log --daemon
```

I have already in Gemfile capistrano-rbenv gem.

**Comment by hbin** [comment]
@imgarylai @ArturT 

Hi, guys. Could you please show me your settings for `capistrano-rbenv` in your deploy.rb?

If you have some statement like `set :rbenv_map_bins, %w{rake gem bundle ruby rails}`, then remove it or update it like this`set :rbenv_map_bins, fetch(:rbenv_map_bins).to_a.concat(%w(your command))`

**Comment by imgarylai** [comment]
@hbin problem solved!

**Comment by hbin** [comment]
@imgarylai :laughing:

**Comment by ArturT** [comment]
@hbin I removed `set :rbenv_map_bins, %w{rake gem bundle ruby rails}` and it helped. Thanks!

**Comment by tirdadc** [comment]
@hbin I'm using [capistrano/rvm](https://github.com/capistrano/rvm/) in this setup, not `capistrano/rbenv`. I don't have any `:rbenv_map_bins` or anything resembling that in my `deploy.rb`:

```
# We use RVM and we want to explicitly set the Ruby version
set :rvm_ruby_version, '2.2.3'
set :rvm_type, :user
set :passenger_restart_with_touch, true
```

**Comment by hbin** [comment]
@tirdadc @gerodp 
Hi, It seems like that the RVM using a new map_bins.

Try to add the following line to your deploy.rb file:

```ruby
set :rvm1_map_bins, fetch(:rvm1_map_bins).to_a.concat(%w(sidekiq sidekiqctl))
```

**Comment by giuseb** [comment]
Using `rbenv`, but no `:rbenv_map_bins` in my config/deploy.
Reverting to 0.5.3 allowed me to deploy, but what is the actual fix here?

**Comment by ziazek** [comment]
Adding the following to deploy.rb worked for me.

```ruby
set :rbenv_map_bins, %w{rake gem bundle ruby rails sidekiq sidekiqctl}
```

**Comment by gaogao1030** [comment]
@ziazek thanks. that worked for me,i think the way is right!

**Comment by ShubhamGupta** [comment]
This must be put in Readme.

**Comment by Aleksandaar** [comment]
If you are using commands like:

     execute <<-CMD
        bundle exec thin start -C config/thin.yml
      CMD

Replace them with something like:
      within current_path do
        execute :bundle, "exec thin restart -C config/thin.yml"
      end

**Comment by goravbhootra** [comment]
If you are using gem rvm1-capistrano3 and rvm, then following needs to be added:

`set :rvm1_map_bins, %w{rake gem bundle ruby puma pumactl}`

**Comment by pmaojo** [comment]
Also 
require "capistrano/rvm"
 must be before
require 'capistrano/sidekiq'
