### ISSUE TITLE
Dependencies version conflict results in failed start sidekiq

### ISSUE THREAD

**Issue by Martin288** [seuros/capistrano-sidekiq#126]
I tried to deploy through capistrano and expected this gem to restart my sidekiq normally, but it seems that it is always failed. Then I ssh login to the server and run the below command manually(I remove the `--daemon` option so I can see outputs from sidekiq):

```sh
~/.rvm/bin/rvm default do sidekiq --index 0 --pidfile /data/apps/xxx/shared/tmp/pids/sidekiq-0.pid --environment production --logfile /data/apps/xxx/shared/log/sidekiq.log --config /data/apps/xxx/current/config/sidekiq.yml
```

It printed out the below error:

```sh
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0.8.7)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/home/dji-plus/.rvm/gems/ruby-2.0.0-p643/gems/bundler-1.10.6/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /data in PATH, mode 040777
/home/dji-plus/.rvm/gems/ruby-2.0.0-p643/gems/bundler-1.10.6/lib/bundler/runtime.rb:34:in `block in setup': You have already activated json 1.7.7, but your Gemfile requires json 1.8.3. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
	from /home/dji-plus/.rvm/gems/ruby-2.0.0-p643/gems/bundler-1.10.6/lib/bundler/runtime.rb:19:in `setup'
	from /home/dji-plus/.rvm/gems/ruby-2.0.0-p643/gems/bundler-1.10.6/lib/bundler.rb:127:in `setup'
	from /home/dji-plus/.rvm/gems/ruby-2.0.0-p643/gems/bundler-1.10.6/lib/bundler/setup.rb:8:in `<top (required)>'
```

And then I decided to prepend `bundle exec` to the `sidekiq` command and it actually resolved the problem and sidekiq restarted as expected:
```sh
~/.rvm/bin/rvm default do bundle exec sidekiq --index 0 --pidfile /data/apps/xxx/shared/tmp/pids/sidekiq-0.pid --environment production --logfile /data/apps/xxx/shared/log/sidekiq.log --config /data/apps/xxx/current/config/sidekiq.yml
```

But I notice that this gem always use `sidekiq` to start, is it the reason why my deployment failed?

**Comment by Martin288** [comment]
I have resolved the problem, just put it below `require 'capistrano/rails'` or `require 'capistrano/bundler'` in `Capfile`, the command `sidekiq` will be mapped to `bundle exec sidekiq` automatically.
