### ISSUE TITLE
Error with sidekiq:monit:config task

### ISSUE THREAD

**Issue by alejandrobarrios07** [seuros/capistrano-sidekiq#185]
Hi, we are having problem when trying running the `sidekiq:monit:config` task, getting this error.

``` 
[dd793c7d] Finished in 0.140 seconds with exit status 0 (successful).
 DEBUG Uploading /tmp/monit.conf 0.0%
  INFO Uploading /tmp/monit.conf 100.0%
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as user@server.com: Exception while executing as user@server.com: wrong number of arguments (given 0, expected 1)

SSHKit::Runner::ExecuteError: Exception while executing as user@server.com: wrong number of arguments (given 0, expected 1)

ArgumentError: wrong number of arguments (given 0, expected 1)

Tasks: TOP => sidekiq:monit:monitor
(See full trace by running task with --trace) 
```

The file upload to the default tmp directory and if we manually move it to the monit folder works correctly, but the task fail and interrupt the execution. We also set all the environments variables that the documentation list and the task still end the execution before complete, throwing us the same error.

``` 
We are using this versions: 
  - Ruby 2.3.1
  - Rails 4.2.6
  - Capistrano 3.4.0 (We try 3.10.0)
  - Capistrano-sidekiq 0.10.0 (We try 0.20.0) 
```

**Comment by skandragon** [comment]
I "fixed" this by moving the lines in `Capfile`:

```
require 'capistrano/sidekiq'
require 'capistrano/sidekiq/monit'
```

to be after these lines:

```
require 'capistrano/rails'
require 'capistrano/rbenv'
require 'capistrano/bundler'
require 'capistrano/rails/migrations'
require 'capistrano/rails/assets'
```

Note that the working order seems to be:

* require the rails stuff
* require sidekiq and sidekiq/monit stuff
* require nginx and puma stuff

Any other order seems to cause something to fail, including a similar message when capistrano is handling nginx stuff, due to what seems to be a conflict between `use_sudo?` in sidekiq's tasks and nginx's tasks.

**Comment by skandragon** [comment]
I was wrong; there is no working order to get sidekiq, sidekiq/monit, nginx, and rails all in the same `Capfile`.  With the order I suggested, I get:

```
SilverGryphon:thing explorer$ bundle exec cap production nginx:create_log_paths
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as user@example.com: wrong number of arguments (given 1, expected 0)


Caused by:
ArgumentError: wrong number of arguments (given 1, expected 0)

Tasks: TOP => nginx:create_log_paths
(See full trace by running task with --trace)
```

**Comment by skandragon** [comment]
BTW, the reason I am guessing at conflict between `use_sudo?` and such is this trace, where I don't expect to see anything monit related, yet I do:

```
** Invoke nginx:create_log_paths (first_time)
** Execute nginx:create_log_paths
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as user@example.com: wrong number of arguments (given 1, expected 0)
/Users/explorer/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/sshkit-1.15.1/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
/Users/explorer/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/sshkit-1.15.1/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'

Caused by:
ArgumentError: wrong number of arguments (given 1, expected 0)
/Users/explorer/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/capistrano-sidekiq-0.20.0/lib/capistrano/tasks/monit.rake:136:in `use_sudo?'
/Users/explorer/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/capistrano3-nginx-2.1.6/lib/capistrano/tasks/nginx.rake:27:in `block in add_sudo_if_required'
/Users/explorer/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/capistrano3-nginx-2.1.6/lib/capistrano/tasks/nginx.rake:26:in `each'
/Users/explorer/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/capistrano3-nginx-2.1.6/lib/capistrano/tasks/nginx.rake:26:in `add_sudo_if_required'
/Users/explorer/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/capistrano3-nginx-2.1.6/lib/capistrano/tasks/nginx.rake:86:in `block (3 levels) in <top (required)>'
/Users/explorer/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/sshkit-1.15.1/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/Users/explorer/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/sshkit-1.15.1/lib/sshkit/backends/abstract.rb:29:in `run'
/Users/explorer/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/sshkit-1.15.1/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => nginx:create_log_paths
The deploy has failed with an error: Exception while executing as user@example.com: wrong number of arguments (given 1, expected 0)
** Invoke deploy:failed (first_time)
** Execute deploy:failed
```

**Comment by alejandrobarrios07** [comment]
i have in this order and the issue continues

```  require 'capistrano/sidekiq'
  require 'capistrano/sidekiq/monit'
  require 'capistrano/puma'
  require 'capistrano/nginx' ```

**Comment by Arslan-Ali-Butt** [comment]
Any solution so far for this issue?

**Comment by skcc321** [comment]
in my case it order helped
# moved -> _require 'capistrano/nginx'_
require 'capistrano/sidekiq'
require 'capistrano/sidekiq/monit'
**require 'capistrano/nginx'** # after monit
