### ISSUE TITLE
Capistrano sidekiq - 2.0.0.beta5 failing the deploy with sidekiq 6

### ISSUE THREAD

**Issue by siddhant-mohan** [seuros/capistrano-sidekiq#259]
Capistrano sidekiq - 2.0.0.beta5 failing the deploy with sidekiq 6. detailed error:

````
00:03 deploy:check:make_linked_dirs
      01 mkdir -p /home/ubuntu/apps/nyxion/shared/config /home/ubuntu/apps/nyxion/shared
    ✔ 01 ubuntu@3.7.125.251 0.198s
#<Thread:0x00007fcfd899f908 /Users/s/.rvm/gems/ruby-2.7.1/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	11: from /Users/s/.rvm/gems/ruby-2.7.1/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
	10: from /Users/s/.rvm/gems/ruby-2.7.1/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:31:in `run'
	 9: from /Users/s/.rvm/gems/ruby-2.7.1/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
	 8: from /Users/s/.rvm/gems/ruby-2.7.1/gems/capistrano-sidekiq-2.0.0.beta5/lib/capistrano/tasks/systemd.rake:7:in `block (3 levels) in eval_rakefile'
	 7: from /Users/s/.rvm/gems/ruby-2.7.1/gems/capistrano-sidekiq-2.0.0.beta5/lib/capistrano/tasks/systemd.rake:126:in `switch_user'
	 6: from /Users/s/.rvm/gems/ruby-2.7.1/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:113:in `as'
	 5: from /Users/s/.rvm/gems/ruby-2.7.1/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:80:in `execute'
	 4: from /Users/s/.rvm/gems/ruby-2.7.1/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:148:in `create_command_and_execute'
	 3: from /Users/s/.rvm/gems/ruby-2.7.1/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:148:in `tap'
	 2: from /Users/s/.rvm/gems/ruby-2.7.1/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:148:in `block in create_command_and_execute'
	 1: from /Users/s/.rvm/gems/ruby-2.7.1/gems/sshkit-1.21.0/lib/sshkit/backends/netssh.rb:170:in `execute_command'
/Users/s/.rvm/gems/ruby-2.7.1/gems/sshkit-1.21.0/lib/sshkit/command.rb:97:in `exit_status=': if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi exit status: 1 (SSHKit::Command::Failed)
if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi stdout: Nothing written
if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi stderr: usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user]
            [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-T timeout] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-T timeout] [-u user] file ...
You cannot switch to user '''' using sudo, please check the sudoers file
	1: from /Users/s/.rvm/gems/ruby-2.7.1/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/Users/s/.rvm/gems/ruby-2.7.1/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing on host 3.7.125.251: if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi exit status: 1 (SSHKit::Runner::ExecuteError)
if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi stdout: Nothing written
if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi stderr: usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user]
            [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-T timeout] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-T timeout] [-u user] file ...
You cannot switch to user '''' using sudo, please check the sudoers file
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host 3.7.125.251: if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi exit status: 1
if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi stdout: Nothing written
if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi stderr: usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user]
            [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-T timeout] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-T timeout] [-u user] file ...
You cannot switch to user '''' using sudo, please check the sudoers file


Caused by:
SSHKit::Command::Failed: if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi exit status: 1
if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi stdout: Nothing written
if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi stderr: usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user]
            [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-T timeout] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-T timeout] [-u user] file ...
You cannot switch to user '''' using sudo, please check the sudoers file

Tasks: TOP => sidekiq:quiet
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing on host 3.7.125.251: if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi exit status: 1
if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi stdout: Nothing written
if ! sudo -u '' whoami > /dev/null; then echo "You cannot switch to user '''' using sudo, please check the sudoers file" 1>&2; false; fi stderr: usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user]
            [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-T timeout] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-T timeout] [-u user] file ...
You cannot switch to user '''' using sudo, please check the sudoers file


** DEPLOY FAILED
** Refer to log/capistrano.log for details. Here are the last 20 lines:

````

My deploy.rb file is:
````
# config valid for current version and patch releases of Capistrano
lock "~> 3.14.1"

set :application, "****"
set :repo_url, "****"
set :puma_threads,    [4, 16]
set :puma_workers,    0

set :scm, :git

set :linked_files, fetch(:linked_files, []).push('config/database.yml', '.env','config/sidekiq.yml', 'config/secrets.yml')
set :linked_dirs, fetch(:linked_dirs, []).push('log', 'tmp/pids', 'tmp/cache', 'tmp/sockets', 'public/system', 'config/key', 'certificate')
append :linked_dirs, '.bundle'

set :default_env, { path: "/opt/ruby/bin:$PATH" }
set :keep_releases, 10
set :debug, true

set :pty, false
set :use_sudo, false
# set :user, 'ubuntu'
set :puma_bind,       "unix://#{shared_path}/tmp/sockets/#{fetch(:application)}-puma.sock"
set :puma_state,      "#{shared_path}/tmp/pids/puma.state"
set :puma_pid,        "#{shared_path}/tmp/pids/puma.pid"
set :puma_access_log, "#{release_path}/log/puma.error.log"
set :puma_error_log,  "#{release_path}/log/puma.access.log"
set :ssh_options,     { forward_agent: true, user: 'ubuntu', keys: %w(~/.ssh/id_rsa) }
set :puma_preload_app, true
set :puma_worker_timeout, nil
set :puma_init_active_record, true  # Change to true if using ActiveRecord

set :rvm_map_bins, fetch(:rvm_map_bins).to_a.concat(%w(sidekiq sidekiqctl))

# set the locations that we will look for changed assets to determine whether to precompile
set :assets_dependencies, %w[app/assets lib/assets vendor/assets Gemfile.lock config/routes.rb]

# Sidekiq Configuration
set :sidekiq_config, 'config/sidekiq.yml'
set :sidekiq_roles, %i[worker]

# sidekiq systemd options
set :sidekiq_service_unit_name => 'sidekiq'
set :sidekiq_service_unit_user => :user # :system
set :sidekiq_enable_lingering => true
set :sidekiq_lingering_user => nil

# set :bundle_flags,      '--quiet' # this unsets --deployment, see details in config_bundler task details
# set :bundle_path,       nil
# set :bundle_without,    nil


namespace :puma do
  desc 'Create Directories for Puma Pids and Socket'
  task :make_dirs do
    on roles(:app) do
      execute "mkdir #{shared_path}/tmp/sockets -p"
      execute "mkdir #{shared_path}/tmp/pids -p"
    end
  end

  before :start, :make_dirs
end

namespace :deploy do
  desc 'Make sure local git is in sync with remote.'
  task :check_revision do
    on roles(:app) do
      unless `git rev-parse HEAD` == `git rev-parse origin/#{fetch(:branch)}`
        puts "WARNING: HEAD is not the same as origin/#{fetch(:branch)}"
        puts 'Run `git push` to sync changes.'
        exit
      end
    end
  end

  desc 'Config bundler'
  task :config_bundler do
    on roles(/.*/) do
      execute :bundle, :config, '--local deployment true'
      execute :bundle, :config, '--local without "development test"'
      execute :bundle, :config, '--local path vendor'
    end
  end

  desc 'Initial Deploy'
  task :initial do
    on roles(:app) do
      before 'deploy:restart', 'puma:start'
      invoke 'deploy'
    end
  end

  desc 'Run rake db:seed on a remote server.'
  task :seed do
    on roles :app do
      within release_path do
        with rails_env: fetch(:rails_env) do
          execute :rake, 'db:seed'
        end
      end
    end
  end

  desc 'Restart application'
  task :restart do
    on roles(:worker), in: :sequence, wait: 5 do
      invoke 'sidekiq:restart'
    end
    on roles(:web), in: :sequence, wait: 5 do
      invoke 'puma:stop'
      invoke 'puma:start'
      # within current_path do
      #   with :rails_env => fetch(:rails_env) do
      #     rake 'notes:populate'
      #   end
      # end
    end
  end

  desc 'Start application'
  task :start do
    on roles(:worker), in: :sequence, wait: 5 do
      invoke 'sidekiq:start'
    end
    on roles(:web), in: :sequence, wait: 5 do
      invoke 'puma:start'
    end
  end

  desc 'Stop application'
  task :stop do
    on roles(:worker), in: :sequence, wait: 5 do
      invoke 'sidekiq:stop'
    end
    on roles(:web), in: :sequence, wait: 5 do
      invoke 'puma:stop'
    end
  end


  after :restart, :clear_cache do
    on roles(:web,:worker), in: :groups, limit: 3, wait: 10 do
      # Here we can do anything such as:
      # within release_path do
      #   execute :rake, 'cache:clear'
      # end
    end
  end

  before 'bundler:install', 'deploy:config_bundler'
  # before :starting, :check_revision
  # before :starting, "figaro_yml:setup"
  # before :starting, 'linked_files:upload_files'
  after  :finishing, :compile_assets
  after  :finishing, :cleanup
  after  :published, 'bundler:clean'
  after  :publishing, 'deploy:restart'

end
# ps aux | grep puma    # Get puma pid
# kill -s SIGUSR2 pid   # Restart puma
# kill -s SIGTERM pid   # Stop puma

````

https://github.com/seuros/capistrano-sidekiq/issues/258

**Comment by Paprikas** [comment]
Hi, @siddhant-mohan. I believe this commit breaks systemd config file:
https://github.com/seuros/capistrano-sidekiq/commit/6ef104f3826b13cc8f0db13f477048511d6fe96c
I do not know the details behind bundle bundler namings, maybe the whole config line is wrong.
But previous version (commit) is working.
Just use this line in Gemfile
`gem "capistrano-sidekiq", github: "seuros/capistrano-sidekiq", ref: "55465f3392f2b653a10dda481ed69e089cc081ff"`

Here is my config file
Before commit (renaming):
ExecStart=/usr/local/rbenv/bin/rbenv exec bundler exec sidekiq -e production

After:
ExecStart=RBENV_ROOT=/usr/local/rbenv RBENV_VERSION=2.7.1 /usr/local/rbenv/bin/rbenv exec bundle exec sidekiq -e production

So basicly its just a bad path to executable.

**Comment by krthi** [comment]
Any update or workaround for this issue ?

**Comment by hungdinhvan** [comment]
Hello,

I also had the same problem, after a few hours of research, I fixed it with the following:
1. Write a service sidekiq.service according to the following instructions:
https://dev.to/kevinluo201/start-sidekiq-6-as-daemon-in-production-environment-on-ubuntu-20-04-4m7b
In case i use command
```
systemctl --user {start,stop,restart} sidekiq
```
2. Write a capistrano task as follows:
```
/lib/capistrano/task/sidekiq.rake

namespace :sidekiq do
    desc "Overwritten sidekiq:{start, stop, restart}"
    task :restart do
      puts "Overwriting sidekiq:restart"
      on roles(:all) do |host|
        execute :systemctl, '--user','restart', 'sidekiq'
      end
    end
    task :start do
      puts "Overwriting sidekiq:start"
      on roles(:all) do |host|
        execute :systemctl, '--user','start', 'sidekiq'
      end
    end
    task :stop do
      puts "Overwriting sidekiq:stop"
      on roles(:all) do |host|
        execute :systemctl, '--user','stop', 'sidekiq'
      end
    end
end
```
Final, Of course install deploy.rb with Capfile
```
require 'capistrano/sidekiq'
install_plugin Capistrano::Sidekiq  # Default sidekiq tasks
install_plugin Capistrano::Sidekiq::Systemd
```
Hope it helps you or someone.

**Comment by fpapadamis** [comment]
Hi @al0xd , I have tried your solution but it does not work.
Using `--trace` flag in my `cap deploy` command I see that capistrano is trying to run `sidekiq:quiet` and it produces the error about sudoers.
Any recommendations?

**Comment by KhanhVanCong** [comment]
> Hi @al0xd , I have tried your solution but it does not work. Using `--trace` flag in my `cap deploy` command I see that capistrano is trying to run `sidekiq:quiet` and it produces the error about sudoers. Any recommendations?

I also have this problem. I found the solution following this tutorial: [https://medium.com/@umeriqbal256/sidekiq-configuration-on-aws-with-capistrano-e4e63f15f261](url).
I think this problem is about we forgot to set the config `user`: 
`server 'your_server_ip', port: 'your_server_port', user: 'your_user_deploy', roles: [:web, :app, :db], primary: true`

**Comment by fpapadamis** [comment]
> > Hi @al0xd , I have tried your solution but it does not work. Using `--trace` flag in my `cap deploy` command I see that capistrano is trying to run `sidekiq:quiet` and it produces the error about sudoers. Any recommendations?
> 
> I also have this problem. I found the solution following this tutorial: [https://medium.com/@umeriqbal256/sidekiq-configuration-on-aws-with-capistrano-e4e63f15f261](url). I think this problem is about we forgot to set the config `user`: `server 'your_server_ip', port: 'your_server_port', user: 'your_user_deploy', roles: [:web, :app, :db], primary: true`

I ended up using custom made tasks for handling the systemd service.

Removed `Capistrano::Sidekiq::Systemd` from `Capfile`:
```ruby
require 'capistrano/sidekiq'
install_plugin Capistrano::Sidekiq
# install_plugin Capistrano::Sidekiq::Systemd
```

Created tasks in `deploy.rb`:
```ruby
namespace :sidekiq do
  desc 'Overwritten sidekiq:{start, stop, reload}'
  
  task :reload do
    on roles(:background_services) do
      fetch(:sidekiq_service_unit_name).each do |service|
        within release_path do
          execute :systemctl, '--user', 'reload', service
        end
      end
    end
  end

  task :start do
    on roles(:background_services) do
      fetch(:sidekiq_service_unit_name).each do |service|
        within release_path do
          execute :systemctl, '--user', 'start', service
        end
      end
    end
  end

  task :stop do
    on roles(:background_services) do
      fetch(:sidekiq_service_unit_name).each do |service|
        within release_path do
          execute :systemctl, '--user', 'stop', service
        end
      end
    end
  end
end
```

The `:sidekiq_service_unit_name` is declared in each environment `.rb` file like:
```ruby
set :sidekiq_service_unit_name, ['sidekiq', 'sidekiq_2', 'sidekiq_3']
```

**Comment by al0xd** [comment]
> > > Hi @al0xd , I have tried your solution but it does not work. Using `--trace` flag in my `cap deploy` command I see that capistrano is trying to run `sidekiq:quiet` and it produces the error about sudoers. Any recommendations?
> > 
> > 
> > I also have this problem. I found the solution following this tutorial: [https://medium.com/@umeriqbal256/sidekiq-configuration-on-aws-with-capistrano-e4e63f15f261](url). I think this problem is about we forgot to set the config `user`: `server 'your_server_ip', port: 'your_server_port', user: 'your_user_deploy', roles: [:web, :app, :db], primary: true`
> 
> I had included `user: 'your_user_deploy'` but it did not work. I ended up using custom made tasks for handling the systemd service.
> 
> Removed `Capistrano::Sidekiq::Systemd` from `Capfile`:
> 
> ```ruby
> require 'capistrano/sidekiq'
> install_plugin Capistrano::Sidekiq
> # install_plugin Capistrano::Sidekiq::Systemd
> ```
> 
> Created tasks in `deploy.rb`:
> 
> ```ruby
> namespace :sidekiq do
>   desc 'Overwritten sidekiq:{start, stop, reload}'
>   
>   task :reload do
>     on roles(:background_services) do
>       fetch(:sidekiq_service_unit_name).each do |service|
>         within release_path do
>           execute :systemctl, '--user', 'reload', service
>         end
>       end
>     end
>   end
> 
>   task :start do
>     on roles(:background_services) do
>       fetch(:sidekiq_service_unit_name).each do |service|
>         within release_path do
>           execute :systemctl, '--user', 'start', service
>         end
>       end
>     end
>   end
> 
>   task :stop do
>     on roles(:background_services) do
>       fetch(:sidekiq_service_unit_name).each do |service|
>         within release_path do
>           execute :systemctl, '--user', 'stop', service
>         end
>       end
>     end
>   end
> end
> ```
> 
> The `:sidekiq_service_unit_name` is declared in each environment `.rb` file like:
> 
> ```ruby
> set :sidekiq_service_unit_name, ['sidekiq', 'sidekiq_2', 'sidekiq_3']
> ```

Hi @fpapadamis 
If you could provide more of your error logs, I will have a better understanding of your issue and hopefully be able to help with something. If I'm not mistaken, it seems like the issue you're facing is related to user permissions during deployment. This issue can be resolved by granting sudo privileges to the user and bypassing the password for this user.
