### ISSUE TITLE
undefined local variable or method `fetch_systemd_unit_path'

### ISSUE THREAD

**Issue by heaven** [seuros/capistrano-sidekiq#280]
Stacktrace
```
00:00 sidekiq:uninstall
      01 systemctl --user disable sidekiq
      01 Removed /home/deploy/.config/systemd/user/default.target.wants/sidekiq.service.
    ✔ 01 deploy@64.225.104.136 0.266s
#<Thread:0x00007feb9c978788@/Users/heaven/.rvm/gems/ruby-2.6.6@qarib/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	5: from /Users/heaven/.rvm/gems/ruby-2.6.6@qarib/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
	4: from /Users/heaven/.rvm/gems/ruby-2.6.6@qarib/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:31:in `run'
	3: from /Users/heaven/.rvm/gems/ruby-2.6.6@qarib/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
	2: from /Users/heaven/.rvm/gems/ruby-2.6.6@qarib/gems/capistrano-sidekiq-2.0.0/lib/capistrano/tasks/systemd.rake:61:in `block (3 levels) in eval_rakefile'
	1: from /Users/heaven/.rvm/gems/ruby-2.6.6@qarib/gems/capistrano-sidekiq-2.0.0/lib/capistrano/tasks/systemd.rake:124:in `switch_user'
/Users/heaven/.rvm/gems/ruby-2.6.6@qarib/gems/capistrano-sidekiq-2.0.0/lib/capistrano/tasks/systemd.rake:67:in `block (4 levels) in eval_rakefile': undefined local variable or method `fetch_systemd_unit_path' for #<SSHKit::Backend::Netssh:0x00007feb9c9832c8> (NameError)
	1: from /Users/heaven/.rvm/gems/ruby-2.6.6@qarib/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/Users/heaven/.rvm/gems/ruby-2.6.6@qarib/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as deploy@64.225.104.136: undefined local variable or method `fetch_systemd_unit_path' for #<SSHKit::Backend::Netssh:0x00007feb9c9832c8> (SSHKit::Runner::ExecuteError)
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@64.225.104.136: undefined local variable or method `fetch_systemd_unit_path' for #<SSHKit::Backend::Netssh:0x00007feb9c9832c8>


Caused by:
NameError: undefined local variable or method `fetch_systemd_unit_path' for #<SSHKit::Backend::Netssh:0x00007feb9c9832c8>

Tasks: TOP => sidekiq:uninstall
(See full trace by running task with --trace)
```

In addition to the undefined variable I've also found there's another bug in the uninstall task here:
```
execute :rm, '-f', File.join(fetch(:service_unit_path, fetch_systemd_unit_path), fetch(:sidekiq_service_unit_name))
```

This should be `"#{fetch(:sidekiq_service_unit_name)}.service"`.

**Comment by seuros** [comment]
@heaven can you try master ?

**Comment by antarr** [comment]
I have the same issue. I've already tried master

**Comment by seuros** [comment]
This setting was removed in master. All the gem was simplified and tested.
If this issue persist open a PR in  https://github.com/seuros/capistrano-example-app  so i can replicate it.

Thank you for your report
