### ISSUE TITLE
Sidekiq fails to start via deploy, but does start via sidekiq:start

### ISSUE THREAD

**Issue by matt-morris** [seuros/capistrano-sidekiq#78]
When manually calling the start task, i.e. `cap staging sidekiq:start`, everything works just like it's supposed to. Sidekiq starts and everything is wonderful. However, the deploy task fails to start Sidekiq. 

From `cap staging sidekiq:start`:
```
INFO [bd06ac04] Running /opt/rbenv/bin/rbenv exec bundle exec sidekiq --index 0 --pidfile /home/apps/my_app/current/tmp/sidekiq-0.pid --environment staging --logfile /home/apps/my_app/shared/log/sidekiq.log --daemon as deploy@myhost
```

From `sidekiq.log`:
```
2015-04-14T15:04:28.970Z 15803 TID-ox6iueuu0 INFO: Booting Sidekiq 3.3.3 with redis options {:url=>"redis://xx.xx.xx.xx:6379/0"}
2015-04-14T15:04:29.774Z 15803 TID-ox6iueuu0 INFO: Running in ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
2015-04-14T15:04:29.774Z 15803 TID-ox6iueuu0 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2015-04-14T15:04:29.774Z 15803 TID-ox6iueuu0 INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org/pro
2015-04-14T15:04:30.112Z 15895 TID-ouecgm9i0 INFO: Booting Sidekiq 3.3.3 with redis options {:url=>"redis://xx.xx.xx.xx:6379/0"}
2015-04-14T15:04:30.924Z 15895 TID-ouecgm9i0 INFO: Running in ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
2015-04-14T15:04:30.924Z 15895 TID-ouecgm9i0 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2015-04-14T15:04:30.924Z 15895 TID-ouecgm9i0 INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org/pro
```

From `cap staging deploy`:
```
INFO [fec5414e] Running /opt/rbenv/bin/rbenv exec bundle exec sidekiq --index 0 --pidfile /home/apps/my_app/current/tmp/sidekiq-0.pid --environment staging --logfile /home/apps/my_app/shared/log/sidekiq.log --daemon as deploy@myhost
```

From `sidekiq.log`:
```
No such file or directory @ rb_sysopen - /home/apps/my_app/current/tmp/sidekiq-0.pid
/home/apps/my_app/shared/bundle/ruby/2.2.0/gems/sidekiq-3.3.3/lib/sidekiq/cli.rb:352:in `initialize'
/home/apps/my_app/shared/bundle/ruby/2.2.0/gems/sidekiq-3.3.3/lib/sidekiq/cli.rb:352:in `open'
/home/apps/my_app/shared/bundle/ruby/2.2.0/gems/sidekiq-3.3.3/lib/sidekiq/cli.rb:352:in `write_pid'
/home/apps/my_app/shared/bundle/ruby/2.2.0/gems/sidekiq-3.3.3/lib/sidekiq/cli.rb:42:in `parse'
/home/apps/my_app/shared/bundle/ruby/2.2.0/gems/sidekiq-3.3.3/bin/sidekiq:7:in `<top (required)>'
/home/apps/my_app/shared/bundle/ruby/2.2.0/bin/sidekiq:23:in `load'
/home/apps/my_app/shared/bundle/ruby/2.2.0/bin/sidekiq:23:in `<main>'
No such file or directory @ rb_sysopen - /home/apps/my_app/current/tmp/sidekiq-1.pid
/home/apps/my_app/shared/bundle/ruby/2.2.0/gems/sidekiq-3.3.3/lib/sidekiq/cli.rb:352:in `initialize'
/home/apps/my_app/shared/bundle/ruby/2.2.0/gems/sidekiq-3.3.3/lib/sidekiq/cli.rb:352:in `open'
/home/apps/my_app/shared/bundle/ruby/2.2.0/gems/sidekiq-3.3.3/lib/sidekiq/cli.rb:352:in `write_pid'
/home/apps/my_app/shared/bundle/ruby/2.2.0/gems/sidekiq-3.3.3/lib/sidekiq/cli.rb:42:in `parse'
/home/apps/my_app/shared/bundle/ruby/2.2.0/gems/sidekiq-3.3.3/bin/sidekiq:7:in `<top (required)>'
/home/apps/my_app/shared/bundle/ruby/2.2.0/bin/sidekiq:23:in `load'
/home/apps/my_app/shared/bundle/ruby/2.2.0/bin/sidekiq:23:in `<main>'
```

It seems like the same command is being run in both cases, but clearly something different is going on. Am I just misunderstanding something? Please let me know if you need any more information to help clarify the situation. 

Note: The error message I'm receiving matches #71, but I'm opening a new issue as the behavior I'm seeing is a little different, since Sidekiq _will_ start if called by itself.

**Comment by seuros** [comment]
Could you show me your custom sidekiq options ?

**Comment by matt-morris** [comment]
#### /config/initializers/sidekiq.rb
```
Sidekiq.configure_server do |config|
  config.redis = { url: "redis://#{Rails.application.secrets.redis_host}:#{Rails.application.secrets.redis_port}/0" }
end

Sidekiq.configure_client do |config|
  config.redis = { url: "redis://#{Rails.application.secrets.redis_host}:#{Rails.application.secrets.redis_port}/0" }
end
```

#### /config/deploy/staging.rb
```
set :pty, false

set :sidekiq_role, :web
set :sidekiq_env, 'staging'
set :sidekiq_processes, 2

set :sidekiq_pid, File.join(current_path, 'tmp', 'sidekiq.pid')
```

#### /config/sidekiq.yml
```
---
:verbose: false
:concurrency: 25
:timeout: 30
:queues:
  - [critical, 3]
  - [default, 2]
  - [low, 1]
```

#### /config/application.rb
```
...
config.active_job.queue_adapter = :sidekiq
...
```

**Comment by seuros** [comment]
change `set :sidekiq_pid, File.join(current_path, 'tmp', 'sidekiq.pid')` to `set :sidekiq_pid, File.join(shared_path, 'tmp', 'sidekiq.pid')`

**Comment by seuros** [comment]
or just remove it to use default.

**Comment by matt-morris** [comment]
okay, well, that seems to have done the trick, although i'm struggling to understand why.

**Comment by seuros** [comment]
current_path is set everytime you run the deploy to a new release folder. 
Cap tries to shutdown sidekiq using pids that are inexistant in the new folder (current_path), that why you see the error. By setting them in a stable path, we can shutdown sidekiq without any issue.

**Comment by matt-morris** [comment]
okay, that makes sense.  thank you for the quick reply.
